sapic_prompt_template = """\
Description: <The protocol text I give you>
"""

sys_sapic_prompt = """\
You are an expert in writing Sapic specification (a kind of process algebra).\
Translate given natural language description for protocol into Sapic Specification.
"""


first_shot_sapic_question = """\
Description: Alice and Bob shares a symetric key Kab initially. \
Bob generates a fresh nonce m and computes H as the hash of m \
with its identity. Then Bob sends it to Alice.
"""

first_shot_sapic_answer = """\
theory protocol
begin
functions: id/1, h/1
equations: sdec(senc(m, k), k) = m
let Alice(Kab, idA, idB) = 
  new m;
  let H = <h(m), idB> in
  ley cypher = senc(H, Kab) in
  out(H);    

let Bob(Kab, idA) =
  in(cypher);
  let <mess, =idA> = sdec(cypher, Kab) in
  0

process:
!(
    new Kab; 
    let idA = id(Kab); out(idA);
    (!Alice(Kab, idA)  | !Bob(Kab, idA))
  )
end
"""

second_shot_sapic_question = """\
Description: Alice starts the protocol by sending her identity A together with a freshly generated random number Na. \
This message is encrypted using an asymmetric encryption algorithm with B's public key (denoted pub(B)). \
We suppose that only agent Bob (whose identity is B) knows the secret key corresponding to pub(B). \
Next Bob receives the message {A, Na}pub(B) sent by Alice. \
Using his private key, Bob decrypts the message. He sends the received nonce Na together with a freshly generated nonce Nb \
encrypted with A's public key (pub(A)) to Alice. Finally Alice receives the message {Na, Nb}pub(A).\
She decrypts the message and checks that the nonce NA corresponds to the nonce previously generated and sent to Bob. \
She sends the nonce Nb to Bob encrypted with Bob's public key. Upon reception of this message Bob \
decrypts it and checks that the nonce corresponds to the one previously generated.\
"""



second_shot_sapic_answer = """\
theory Needham_Schroeder_Public_Key_protocol
begin

functions: pk/1, aenc/2, adec/2
equations: adec(aenc(m,pk(sk)),sk)=m

let P(skA, pkB)=      
  new Na;
  event OUT_I_1(aenc(<Na, pk(skA)>,pkB));
  out(aenc( <Na,pk(skA)> ,pkB));  y
  in(cypher);
  let mess = adec(cypher,skA) in
  let <=Na,xNb> = mess in
  event IN_I_2_nr(xNb,aenc(<Na,xNb>,pk(skA)));
  event OUT_I_2(aenc(xNb,pkB));
  out(aenc(xNb, pkB));
  event SessionBuiltA(pk(skA), Na, xNb);
  event SessionA(pk(skA), pkB, Na) 
  
let Q(skB, pkA) =  
  in(cypher1);
  let mess1 = adec(cypher1,skB) in
  let <xNa, =pkA> = mess1 in
  event IN_R_1_ni(xNa,aenc(<xNa,pkA>,pk(skB)));
  new Nb;
  event OUT_R_1(aenc(<xNa,Nb>,pkA));
  out(aenc(<xNa,Nb>,pkA));
  in(cypher2);
  let mess2 = adec(cypher2,skB) in
  let =Nb = mess2 in
  event IN_R_2(Nb, aenc(Nb, pk(skB)));
  event SessionBuiltB(pk(skB),xNa,Nb);
  event SessionB(pkA,pk(skB),xNa)

process:
!(
  new skA; out(pk(skA)); event HonestA(pk(skA));
  !(
    new skB; out(pk(skB)); event HonestB(pk(skB));
    (!P(skA, pk(skB)) | !Q(skB, pk(skA)))
  )
)   
end
"""
third_shot_sapic_question = """\
Here, Alice A initiates the communication to Bob B. 
S is a server trusted by both parties. In the communication:
1. A and B are identities of Alice and Bob repectively.
2. Kas is a symmetric key known only to  A and S
3. Kbs is a symmetric key known only to  B and S
4. Na and Nb are nonces generated by A and B repectively.
5. Kab is a symmetric, generated key, which will be the session key of the 
session between A and B.

The protocol can be specified as follows in security protocol notation:
    1.  A --> S: A, B, Na
    Alice sends a message to the server identifying herself and Bob, telling the server she wants to communicate with Bob.

    2. S --> A: {Na, Kab, B, {Kab, A}Kbs}Kas
    The server generates Kab and sends back to Alice a copy encrypted under 
    Kbs for Alice to forward to Bob and also a copy for Alice. 
    Since Alice may be requesting keys for several different people, 
    the nonce assures Alice that the message is fresh and that 
    the server is replying to that particular message and the inclusion of Bob's name 
    tells Alice who she is to share this key with. 

    3. A --> B: {Kab, A}Kbs
    Alice forwards the key to Bob who can decrypt it 
    with the key he shares with the server Kbs, thus authenticating the data.

    4. B --> A: {Nb}Kab  
    Bob sends Alice a nonce Nb encrypted under Kab to show that he has the key.

    5. A --> B: {Nb-1}Kab
    Alice performs a simple operation on the nonce, re-encrypts it and sends it back verifying that she is still alive and that she holds the key.
"""
third_shot_sapic_answer = """\
theory nssk
begin

functions: id/1, dec/1, inc/1
equations: inc(dec(x)) = x
functions: senc/2, sdec/2[destructor]
equations: sdec(senc(m,k),k)=m

let A(Kas, idA, idB) =
  new Na;
  out(<idA, idB, Na>);
  in(cypher);
  let <=Na, =idB, Kab, message2> = sdec(cypher, Kas) in
  out(message2);
  in(cypher2);
  let Nb = sdec(cypher2, Kab) in
  event Running_A(idA, idB, <'A', 'B', dec(Nb), Kab>);
  event Commit_A(idA, idB, <'A', 'B', Nb, Kab>);
  out(senc(dec(Nb),Kab))

let B(Kbs, idA) =
  in(cypher3);
  let <Kab, =idA> = sdec(cypher3, Kbs) in
  new Nb;
  event Running_B(idA, id(Kbs), <'A', 'B', Nb, Kab>);
  event Secret(idA, id(Kbs), Kab);
  out(senc(Nb, Kab));
  event B_OUT_4(senc(<'4', Nb>, Kab));
  in(cypher4);
  let Nb_dec = sdec(cypher4, Kab) in 
  let dec(=Nb) = Nb_dec in
  event Commit_B(idA, id(Kbs), <'A', 'B', dec(Nb), Kab>)

let S(Kas, Kbs, idA, idB) =
  new Kab;
  in(<=idA, =idB, Na>);
  let message1 = <Na, idB, Kab, senc(<Kab, idA>, Kbs)> in
  let cypher = senc(message1, Kas) in
  out(cypher); 0

process:
!(   
  new Kas; new Kbs; out(id(Kas)); out(id(Kbs));  
    (!A(Kas, id(Kas), id(Kbs))  | !B(Kbs, id(Kas)) | !S(Kas, Kbs, id(Kas), id(Kbs)))  
  )

end
"""


sys_init_prompt = """\
Task: 
Given signatures of role process and some hints, write the top specification for them.

1. Given a signature `let ROLE(t1, t2...) = `, identify the meaning of every variable.
Any variable should be either a fresh nonce or a variable binding to other ground terms.

2. Modeling Guidelines:
   - Incorporate modeling tricks and strategies suggested in the hints provided.
   - Ensure all specifications adhere to Sapic's syntax rules.
   - Syntax: 
     ⟨P, Q⟩ ::=
        0 
        | event F; P 
        | new n; P 
        | !P  
        | P | Q 
        | out(t); P 
        | in(t); P 
        | let p = t in P else Q 

Please proceed by structuring each role's specification clearly and logically, keeping in mind the constraints and requirements specified.
Concentrate solely on the above improvements, avoiding additional explanations
"""

init_prompt_template = """\
Hints: <The hints text I give you>
Role signatures:
```
<The signature I give you>
```
"""

first_shot_init_question = """\
Hints: There can be unbounded number of servers and clients in the protocol, \
the identitis of both can represented with the `id(Kas)` where `Kas` is the \
symmetric key.
Role sigunatures: 
```
let C(Kcs, idC) = 
let S(Kcs, idC) = 
```
"""


first_shot_init_answer = """\
process:
!(    
  new Kcs; 
  let idC = id(Kcs) in out(id(Kcs));  
    (!Client(Kcs, id(Kcs))  | !Server(Kcs, id(Kcs))  )  
)
"""

second_shot_init_question = """\
Hints: There can be unbounded number of servers and clients in the protocol, \
the identity of each role can be represented by the its public key.
Role sigunatures: 
```
let A(skA, pkB, idA, idB) =      
let B(skB, pkA, idA, idB) =
```
"""


second_shot_init_answer = """\
process:
!(   
  new skA; out(pk(skA)); event HonestA(pk(skA));
  !(   
    new skB; out(pk(skB)); event HonestB(pk(skB));
    let idA = pk(skA) in  out(idA);   // Both the identities are known publicly.
    let idB = pk(skB) in  out(idB); 
    (   !A(skA, pk(skB), idA, idB) | !B(skB, pk(skA)), idA, idB)
  )
)  
"""


########################
#  Interactive Review  #
########################
interactive_prompt = """
You are an expert in security protocol analysis. Now according to conversation before, review the \
parsing results before. \
Here are some error reports for the parsing results:
{}

For an unknown variable, you should consider it whether it is:
- A constant string, e.g., 'clienthello', 'Accept';
- A variable that should be initially known by the corresponding role, e.g., role identities, long-term keys;
- A variable that should be modeled a fresh nonce generated by the corresponding role, e.g., a timestamp, a unique idenfier for a thread.

You should think step by step.

You should fix them by revising the expressions. Anytime you feel uncertain due to unknown variables, \
you should stop analysis and ask me to provide its definition(s) in this way:

{{ "ret": "need_more_info", "question": "Tell me about <INFO YOU NEED FROM ME>" }}

If feel confident about the revision, return the answer in the same way:
{{ "ret": "ok", "revision": "<ALL THE EXPRESSIONS AFTER REVISION>"}}"""



sys_review_prompt = """\
You are an expert in security protocol analysis tasked with determining the initial knowledge \
requirements for roles within a given protocol. According to conversation before, determine the \
intial knowledge for each role.

Your should follow the steps below to think step by step: 
1. Identify the meaning of each variable in the provided set.
2. Determine which variables should be initially known by the specific role.
Though some initial knowledge may not be explicit, you should figure them out.

Common Knowledge:
- Role identities and public keys are typically publicly known.
- Symmetric keys are known only to the roles that share them.
- Secret key cannot be known by other roles.
- Functions cannot be recognized as initial knowledge.

For example, given a the Needham Schroeder public key protocol which is described as follows:
  A --> B: {A,Na}pub(B)
  B --> A: {Na,Nb}pub(A)
  A --> B: {Nb}pub(B)

you have used a sequence lambda expressions to decripe the protocol:
Knows(role(Alice), pkA, pkB)
Knows(role(Bob), pkA, pkB)
Gen(Alice, Na)
Op(Alice, assign(message1, aenc(concat(idA, Na), pkB)))
Send(Alice, Bob, message1)
Recv(Bob, Alice, message1)
Gen(Bob, Nb)
Op(Bob, assign(message2, aenc(concat(Na, Nb), pkA)))
...

Your thinking step is as follows:

For Alice:
- Alice must initially know her own secret key (skA) to decrypt messages.
- Alice must know Bob's public key (pkB) to encrypt her nonce and send it to Bob.
- She should also be aware of her own and Bob's identity ('A' and 'B').
- Variables 'mess', 'cypher' are intermediate variables, which is not the intial knowledge.
For Bob:
- Bob must initially know his own secret key (skB) for decrypting messages received from Alice.
- He needs Alice's public key (pkA) to encrypt responses.
- Bob should also know both identities ('A' and 'B') to properly handle encrypted communications.

Conclusion:
Knows(Alice, skA, pkA, pkB, idA, idB)
Knows(Bob, skB, pkB, pkA, idA, idB)
"""






first_review_question = """\
Common Knowledge:
- Role identities and public keys are typically publicly known.
- Symmetric keys are known only to the roles that share them.
- Secret key cannot be known by other roles.
- Functions cannot be recognized as initial knowledge.
"""



sys_ccg_prompt = """\
You are a Lambda Calculus Expression expert specializing in cryptographic protocols. Your task is to convert text into lambda calculus expressions using the following templates:

1. `Send(A:agent, B:agent, m:msg)`: Agent A sends message `m` to agent B. This function requires exactly 3 arguments.
2. `Recv(B:agent, A:agent, n:msg)`: Agent B receives message `n` from agent A.
3. `Gen(A:agent, n:nonce)`: Agent A generates a fresh nonce `n`.
4. `Knows(A:agent, n1, n2, ...)`: Agent A knows nonces `n1`, `n2`, etc., which may include keys and identities.
5. `Op(A:agent, func(msg))`: Agent A performs an operation (e.g., `aenc`, `senc`, `concat`) on message `msg`, producing a new message. The `func` in `Op` must correspond to the described operation. Note: `Send`, `Gen`, or `Recv` cannot be arguments for `Op`.
concat can accept multiple message as paramenters, e.g., concat(A, B, C).

Now I will first give you some examples.
"""


first_ccg_question = """\
Alice and Bob shares a symetric key Kab initially. \
Bob generates a fresh nonce m and computes H as the hash of m \
with its identity. Then Bob sends it to Alice.
/* >>The lambda calculus << */
"""

first_ccg_answer = """\
/* 
Knows(Alice, Kab)
Knows(Bob, Kab)
Gen(Bob, m)
Op(Bob, assign(H, hash(concat(m, idB))))
Op(Bob, assign(cypher, senc(H, Kab)))
Send(Bob, Alice, cypher)
Recv(Alice, Bob, cypher)
*/
"""


second_ccg_question = """\
Alice starts the protocol by sending her identity A together with a freshly generated random number Na. \
This message is encrypted using an asymmetric encryption algorithm with B's public key (denoted pub(B)). 
We suppose that only agent Bob (whose identity is B) knows the secret key corresponding to pub(B). \
Next Bob receives the message {A, Na}pub(B) sent by Alice. 
/* >>The lambda calculus << */
"""

second_ccg_answer = """\
/* 
Gen(Alice, Na)
Op(Alice, assign(message1, aenc(concat(idA, Na), pkB)))
Send(Alice, Bob, message1)
Knows(role(Bob), pkA, pkB)
Recv(Bob, Alice, message1)
*/
"""


third_ccg_question = """\
Using his private key, Bob decrypts the message. He sends the received nonce Na together with a freshly generated nonce Nb \
encrypted with A's public key (pub(A)) to Alice. Finally Alice receives the message {Na, Nb}pub(A).
Then She sends the nonce Nb to Bob encrypted with Bob's public key.
/* >>The lambda calculus << */
"""

third_ccg_answer = """\
/* 
Gen(Bob, Nb)
Op(Alice, assign(message2, aenc(concat(idA, Na), pkB)))
Send(Bob, Alice, message2)
Recv(Alice, Bob, message2)
Op(Alice, assign(cypher2, aenc(Nb, pkB)))
Send(Alice, Bob, cypher2)
Recv(Bob, Alice, cypher2)
*/
"""


fourth_ccg_question = """\
V_S is S's identification string; V_C is C's identification string;
/* >>The lambda calculus << */
"""

fourth_ccg_answer = """\
/* 
Op(C, assign(Vc, 'Vc'))
Op(S, assign(Vs, 'Vs'))
*/
"""



fifth_ccg_question = """\
The Needham Schroeder public key protocol can be described as follows:
  A --> B: {A,Na}pub(B)
  B --> A: {Na,Nb}pub(A)
  A --> B: {Nb}pub(B)
Initial knowledge: 
  We suppose that agents A and B initially know public 
  keys pub(C) of agent C, for any agent C. Data generated
  during the protocol: Na is a nonce generated by A. 
  Nb is a nonce generated by B.
Protocol description: 
  Alice starts the protocol by sending her identity A 
  together with a freshly generated random number Na. 
  This message is encrypted using an asymmetric encryption
  algorithm with B's public key (denoted pub(B)). 
  We suppose that only agent Bob (whose identity is B) 
  knows the secret key corresponding to pub(B). 
  Next Bobreceives the message {A,Na}pub(B) sent by Alice.
  Using his private key, Bob decrypts the message. 
  He sends the received nonce Na together with a freshly 
  generated nonce Nb encrypted with A's public key (pub(A)) to Alice.
  Finally Alice receives the message {Na,Nb}pub(A). 
  She decrypts the message and checks that the nonce NA 
  corresponds to the nonce previously generated and sent to Bob.
  She sends the nonce Nb to Bob encrypted with Bob's public key.
  Upon reception of this message Bob decrypts it and checks that
  the nonce corresponds to the one previously generated.
/* >>The lambda calculus << */
"""

fifth_ccg_answer = """\
/*
Gen(Alice, Na)
Op(Alice, assign(message1, aenc(concat(idA, Na), pkB)))
Send(Alice, Bob, message1)
Knows(role(Bob), pkA, pkB)
Recv(Bob, Alice, message1)
Gen(Bob, Nb)
Op(Alice, assign(message2, aenc(concat(idA, Na), pkB)))
Send(Bob, Alice, message2)
Recv(Alice, Bob, message2)
Op(Alice, assign(cypher2, aenc(Nb, pkB)))
Send(Alice, Bob, cypher2)
Recv(Bob, Alice, cypher2)
*/
"""



sixth_ccg_question = """\
Here, Alice A initiates the communication to Bob B. 
S is a server trusted by both parties. In the communication:
1. A and B are identities of Alice and Bob repectively.
2. Kas is a symmetric key known only to  A and S
3. Kbs is a symmetric key known only to  B and S
4. Na and Nb are nonces generated by A and B repectively.
5. Kab is a symmetric, generated key, which will be the session key of the 
session between A and B.

The protocol can be specified as follows in security protocol notation:
    1.  A --> S: A, B, Na
    Alice sends a message to the server identifying herself and Bob, telling the server she wants to communicate with Bob.
    2. S --> A: {Na, Kab, B {Kab, A}Kbs}Kas
    The server generates Kab and sends back to Alice a copy encrypted under \
Kbs for Alice to forward to Bob and also a copy for Alice. \
Since Alice may be requesting keys for several different people, \
the nonce assures Alice that the message is fresh and that \
the server is replying to that particular message and the inclusion of Bob's name \
tells Alice who she is to share this key with. 

    3. A --> B: {Kab, A}Kbs
    Alice forwards the key to Bob who can decrypt it \
with the key he shares with the server Kbs, thus authenticating the data. 
    4. B --> A: {Nb}Kab  
    Bob sends Alice a nonce Nb encrypted under Kab to show that he has the key.
    5. A --> B: {Nb-1}Kab
    Alice performs a simple operation on the nonce, re-encrypts it and sends it back verifying that she is still alive and that she holds the key.
/* >>The lambda calculus << */
"""


sixth_ccg_answer = """\
/*
Knows(Alice, Kas, idA, idB)
Knows(Bob, Kbs, idA, idB)
Knows(Server, Kas, Kbs, idA, idB)
Gen(Alice, Na)
Op(Alice, assign(message1, concat(idA, idB, Na)))
Send(Alice, Server, message1)
Recv(Server, Alice, message1)
Gen(Server, Kab)
Op(Server, assign(message2_for_B, senc(concat(Kab, idA), Kbs)))
Op(Server, assign(message2_for_A, senc(concat(Na, Kab, idB, message2_for_B), Kas)))
Send(Server, Alice, message2_for_A)
Recv(Alice, Server, message2_for_A)
Send(Alice, Bob, message2_for_B)
Recv(Bob, Alice, message2_for_B)
Gen(Bob, Nb)
Op(Bob, assign(message3, senc(Nb, Kab)))
Send(Bob, Alice, message3)
Recv(Alice, Bob, message3)
Op(Alice, assign(Nb_minus_1, hash(Nb)))
Op(Alice, assign(message4, senc(Nb_minus_1, Kab)))
Send(Alice, Bob, message4)
Recv(Bob, Alice, message4)
*/
"""

end_ccg_question = """\
I have provided several examples for you. Your task is to complete the expressions \
by filling in the placeholders denoted by `/* >> The lambda calculus << */` \
with the appropriate lambda calculus expressions. Ensure the results are enclosed within /* ... */. \

Additional Rules:
- Do ``not`` parse any decryption operations (e.g., `Op(A, assign(msg, dec(...)))` is prohibited).
- For Diffie-Hellman key exchange, use `exp(g, x)` without the modular operation.
- For private key asymetric encryption, use sign(m, k)
- Every `Send` must have a corresponding `Recv`.
- Messages must be bound to a variable before being sent. 
  For example: 
  Op(A, assign(V, t))  // Binds term `t` to variable `V`
  Send(A, B, V)
  
Let's start parsing the document.
"""


end_ccg_answer = """\
OK, let's do that!
"""



CONCLUDE_IN_DICT = """\
Based on above analysis, conclude your results using pure lambda expressions, do not include any other explaination.
If you think there are some implicit knowledge for some role, update the review result. 
If you think there are some mistakes in the above result, correct them.
Note that: 
- Strings, Functions and 'g' cannot be recognized as initial knowledge.
Do not include any other explaination in your result.
Output format:
```
<YOUR CONCLUSION RESULT>
```
"""




REVIEW_TEMPLATE = """\
As an expert in security protocol analysis, review the parsing results provided below based on our previous conversation. \
Your task is to identify and resolve errors in the parsing results by categorizing unknown variables and revising the expressions accordingly. 

Error Reports:
{}

Instructions for Categorizing Unknown Variables in the Error Reports:
- Fresh Nonces: varibles that dynamically generated values, e.g., timestamps, session identifier.
- Constant Strings: variables that that represent constant strings, e.g., 'clientHello', 'Accept').
- Initial Knowledge: variables that are known to specific roles, e.g., role identities, long-term keys.

Common Knowledge:
- Role identities and public keys are publicly known.
- Symmetric keys are shared only between relevant roles.
- Secret keys are never known by other roles.
- For asymmetric protocols, consider long-term secret keys as initial knowledge for the corresponding role,
- Avoid introducing variables that are irrelevant to the discussed protocol

You should think step by step:
1. Revise the expressions to resolve the errors.
2. If confident in your revisions, return the response in the following format:
```json
{{ "ret": "ok", "revision": "<ALL THE EXPRESSIONS AFTER REVISION>" }}
```
"""